project:
  type: website
  output-dir: docs

  
website:
  site-url: "https://ldornfeld.github.io"
  repo-url: "https://github.com/LDornfeld/LDornfeld.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experiences.qmd
        text: Work
      - href: bluesky.qmd
        text: 🦋 Bluesky
      - text: "Blog"
        href: "./blog/" 
  page-footer:
  left: "© 2025 Lars Dornfeld"
  right:
    - text: "Impressum"
      href: impressum.html
        
    

format:
  html:
    css: styles/styles.css
    theme:
      light: flatly
      dark: darkly
    fontsize: 1.0em
    toc: false
    

    



