project:
  type: website

  
website:
  title: "Lars Dornfeld personal website"
  site-url: "https://ldornfeld.github.io"
  repo-url: "https://github.com/LDornfeld/LDornfeld.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experiences.qmd
        text: Work
      - href: bluesky.qmd
        text: 🦋 Bluesky
      - text: "Blog"
        href: "./blog/" 
        
    

format:
  html:
    css: styles/styles.css
    theme:
      light: flatly
      dark: darkly
    toc: false
    output-dir: docs

    



